export const Strings = {
  // LOGIN SCREEN
  USER_NAME: 'User Name',
  PASSWORD: 'Password',
  LOGIN: 'LOGIN',
  LOGIN_SCREEN_KEY: 'Login Screen',
  NAME: 'Name',
  NAME_PLACEHOLDER: 'Enter your Full Name',
  EMAIL: 'Email',
  EMAIL_PLACEHOLDER: 'Enter your Email id.',
  PASS_PLACEHOLDER: 'Enter your Password',
  INVALID_CREDENTIALS: 'Invalid Credentials, Please try again',
  THINK_WITH_AI: 'Think with AI',
  REMEMBER_ME: 'Remember Me',

  // SIGNUP SCREEN
  MOBILE_NUMBER: 'Mobile Number',
  NEED_AN_ACC: 'Need an account?',
  SIGN_UP: 'SIGN UP',
  SIGN_UP_FIRST_CAP: 'Sign Up',
  ALREADY_A_USER: 'Already a user?',
  LOG_IN_FIRST_CAP: 'Log In',
  // -- placeholder Text
  VALID_NAME: 'Enter your name',
  VALID_EMAIL: 'Enter a valid Email id.',
  VALID_MOBILE: 'Enter a valid 10 digit Mobile No.',
  VALID_PASS: 'Enter a 6 char strong password',
  // -- Error Messages
  INVALID_NAME: 'Name cannot be less than 3 letters',
  INVALID_EMAIL: 'Invalid Email Id.',
  INVALID_MOBILE_NUMBER: 'Please enter a valid 10 digit mobile number',
  INVALID_PASS: 'Invalid password combination',
  // -- Success Alert
  YAY: 'Yay!',
  ACCOUNT_OPEN_SUCCESS: 'You have successfully created your account',
  OK: 'OK',

  // DASHBOARD
  DASHBOARD: 'Dashboard',
  LOGIN_SUCCESS:
    'Congratulations, You have successfully Logged In to the portal...',
  WHAT_TO_DO: 'What would you like to do today?',
  SHOW_PROFILE_DETAILS: 'Show My Profile Details',
  START_CHATTING_WITH_AI: 'Start Chatting With AI',
  SHOW_MY_FILES: 'Show My Files',
  UPLOAD_NEW_FILES: 'Upload New Files',
  DELETE_ALL_FILES: 'Delete All Files',
  DELETE_ALL_FILES_CONFIRM: 'Are you sure you want to delete all files?',
  DELETE_SUCCESSFUL: 'All Files Deleted Successfully',
  TRY_ON_DEVICE: "Sorry this feature doesn't work on a simulator...",
  YES: 'Yes',
  NO: 'No',
  CANCEL: 'Cancel',
  WELCOME_TO_FUTURE: 'Welcome To The Future..😍',
  KEEP_NAME_MSG:
    'You can keep a name for your futuristic bot or let us choose one for you',
  GIVE_NAME_TITLE: 'Give a name to your AI buddy..',
  NAME_EG: 'e.g. Lilly',
  CHATBOT_NAMES_ARR: [
    'Sassy',
    'Hip',
    'Friendly',
    'Bubble',
    'Groovy',
    'Witty',
    'Funky',
    'Zap',
    'Light',
    'Pulse',
    'Bumper',
    'Proton',
    'Rapid',
    'Quest',
    'SunShine',
    'Explorer',
    'Cloud',
    'Bonita',
    'Dalia',
    'Howdy',
    'Viral',
    'Foxy',
    'Fido',
    'Nella',
    'Lucky',
    'Morpheus',
    'Miss Clever',
    'Daisy',
    'Gracia',
    'Bigmouth',
    'Stella',
    'Cyber',
    'Dev',
    'Aida',
    'Commander',
    'Connie',
    'Eyebot',
    'Genie',
    'Chatterbot',
    'Gradient',
    'Achievement Bot',
    'Creative Bot',
    'Candy',
    'Harmony',
    'Amazebot',
    'The Botfather',
    'Lovely Bot',
    'Smiles Bot',
    'Happiness Bot',
    'Jokester Bot',
    'Good Vibes Bot',
    'Joy Bot',
    'Amusing Bot',
    'Hearty Bot',
    'Joyous',
    'Helpy',
    'Happy Bot',
    'Chuck',
    'Russel',
    'Dory',
    'Olaf',
    'Comfort',
    'Glad bot',
    'Smiley',
    'Giggles',
    'Buena',
    'Gita',
    'Lilo',
    'Kota',
    'Mona',
    'Ventura',
    'Tobias',
    'Tobin Lykke',
    'Agatha',
    'Cody',
    'Ruth',
    'Levi',
    'Nora',
    'Robo',
    'Transcendence',
    'Hephaestus',
    'Ava',
    'Wall-e',
    'Buzz',
    'Hyperion',
    'Crafty',
    'Intra',
    'Sully',
    'Omon',
    'Omega',
    'Theta',
    'Flash',
    'Olympus',
    'Digital Dave',
    'Simon',
    'Radion',
    'Talk Bot',
    'Proton Bot',
    'Automata',
    'Snap',
    'Zeta',
    'Hydra',
    'Sparkles',
    'Socket',
    'Astor',
    'Chappie',
    'CyBot',
    'Infina',
    'Gemma',
    'Charlie',
    'Optimus',
    'Elixir',
    'Cyd',
    'Percy',
    'Obelus',
    'Kronos',
    'Obelus',
    'Sterling',
    'Garth',
    'Cookie',
    'Eliza',
    'Unimate',
    'Tech',
    'Link',
    'Data',
    'Giga',
    'Byte',
    'Bit',
    'Pixel',
    'Macro',
    'Meta',
    'Swipe',
    'Tag',
    'Chip',
    'Luna',
    'Bruno',
    'Radion',
    'Sputnik',
    'Ash',
    'Ruin',
    'Omon',
    'Percy',
    'Axle',
    'Link',
    'Jet',
    'Gollum',
    'Prima',
    'Jupiter',
    'Tallie',
    'Amerigo',
    'Micro',
    'Automata',
    'Trek',
    'Olympus',
    'Techie',
    'Responder',
    'Screwie',
    'Eva',
    'Silver',
    'Winnie',
    'Buddy',
    'Champ',
    'Amigo',
    'Bubba',
    'Tiny',
    'Buck',
    'Pal',
    'Mouse',
    'Munchkin',
    'Bee',
    'Precious',
    'Bug',
    'Chipmunk',
    'Dottie',
    'Sweetums',
    'Toots',
    'Buttercup',
    'Nugget',
    'Teacup',
    'Oldie',
    'Smarty',
    'Boomer',
    'Rambo',
    'Bond',
    'Speedy Squirt',
    'Reflector',
    'Cowbot',
    'Brainy',
    'Snap',
    'Elixir',
    'Boron',
    'NailHead',
    'Antenna',
    'Mari',
    'Chip',
    'Hector',
    'Logan',
    'Scrap',
    'Sparkles',
    'Cyd',
    'Bracer',
    'Silver',
    'Tracker',
    'Acdator',
    'Stardust',
    'Foxtail',
    'Gabryel',
    'Zax',
    'Augus',
    'Carsin',
    'Tech Buddy',
    'Nerdbot',
    'Mira',
    'Iron Bot',
    'Cybernetic',
    'Digital Dave',
    'Volter Bot',
    'Fintech Bot',
    'SuchBot',
    'Neobot',
    'Supersmart',
    'Gadget',
    'X-Talk',
    'Delilah',
    'Pluto',
    'Franky Automator',
    'Robotnik',
    'Mr. Robot',
    'Botie',
    'Zeus Bots',
    'AI Ninja',
    'Echo',
    'Agent Smith',
    'AI John',
    'Digital Friend',
    'Avatar',
    'Chipbot',
    'Neo',
    'Frankbot',
    'Nemo',
    'Scout',
    'Buster',
    'Bud',
    'Rico',
    'Andrew',
    'Jasper',
    'Robbie the Robot',
    'Alphius',
    'Chandler the Chatbot',
    'Baxi',
    'Albus',
    'Anthony Bot',
    'Henry',
    'Oscar',
    'Roger',
    'Bean',
    'Khal',
    'Edan',
    'Spiky',
    'Fabian',
    'Steve',
    'Enzo',
    'Freddy',
    'Locutus',
    'Buffybot',
    'Marvin',
    'Bender',
    'Bingo',
    'Flash',
    'Maxy',
    'Teddie',
    'Botnik',
    'Casanova',
    'Justin',
    'Seth',
    'John',
    'Morgan',
    'Explorer',
    'Lucy',
    'Erica',
    'Ask Becky',
    'Abbie',
    'Abi',
    'Bailey',
    'Balbo',
    'Ballerina',
    'Bambi',
    'Alice',
    'Daisie',
    'Dandelion',
    'Dane',
    'Alita',
    'Galaxina',
    'Mia',
    'Elly',
    'Lisa',
    'Valerie',
    'Rhoda',
    'Rosie',
    'Freya',
    'Naomi',
    'Pixie',
    'Robotica',
    'Tima',
    'Ida',
    'Jocasta',
    'Tina',
    'Demi',
    'Petra',
    'Alisa',
    'Eve',
    'Metropolis',
    'Sorayama',
    'Ruby',
    'Gloria',
    'Bonnie',
    'Dot',
    'Emma',
    'Jexi',
    'Marvin',
    'Gir',
    'Moony',
    'Tidal',
    'Trek',
    'Aid',
    'Joshua',
    'Collosus',
    'Samaritan',
    'Zen',
    'Orak',
    'Staffer',
    'Ninja help',
    'Lightning',
    'Helpey',
    'Meekan',
    'Luka',
    'Poncho',
    'Chatty Cathy',
    'Rose',
    'Clippy',
    'Digit',
    'Helper',
    'Greetly',
    'Meekan',
    'Receptiviti',
    'Pypestream',
    'Motion',
    'Helper',
    'Kai',
    'Max',
    'Neo',
    'Concierge',
    'Dyno',
    'Echo',
    'Fusion',
    'Aiden',
    'Sage',
    'Sam',
    'Johnny',
    'BizBot',
    'RecruiterBot',
    'Ask Alice',
    'HR Helper',
    'Ask HR',
    'Assistance',
    'Dave',
    'Zen',
    'Lorrie',
    'My Buddy',
    'Sam',
    'Trusty',
    'Watson',
    'Lolly',
    'Ties',
    'Felicia',
    'Holy',
    'Henry',
    'Hank',
    'Harmon',
    'Babel',
    'Marley',
    'Planner',
    'Coordinatie',
    'AI Admin',
    'Linker',
    'Recruitie',
    'Interviewie',
    'Hire Bot',
    'Chatty',
    'Betty',
    'Sophie',
    'Blabbermouth',
    'Hercules',
    'Konversation',
    'Cindy',
    'Growth Bot',
    'Repondeur',
    'Jane',
  ],
  EMOTICONS_ARR: ['😍', '😎', '🤩', '👻', '😻', '😁', '🥳'],
  LOGOUT: 'Log Out',

  // PROFILE DETAILS
  PROFILE_DETAILS: 'Profile Details',

  // UPLOAD NEW FILES
  UPLOAD_FILES: 'Upload Files',
  UPLOAD_IMAGE_FILES: 'Upload Image Files\n(.png/.jpeg)',
  UPLOAD_PDF_FILES: ' Upload PDF Files\n(.pdf)',
  CAMERA_OR_GALLERY: 'Pick Image from..',
  CAMERA: 'Camera',
  GALLERY: 'Gallery',
  UPLOAD_IMAGE: 'Upload Image',
  UPLOAD_PDF: 'Upload PDF',

  // VIEW UPLOAD FILES
  MY_FILES: 'My Files',
  CONFIRM: 'Confirm',
  NO_DATA_FOUND: 'No Data Found...',
  PDF: 'PDF',

  // Error Messages
  OOPS: 'Oops!',
  ALERT: 'Alert',
  ERROR: 'Error',
  SUCCESS: 'Success',
  WARNING: 'Warning',
  INFO: 'Info',
  AW_SNAP: 'Aw Snap!',
  OHH_NO: 'Ohh No!',

  // RN-paper addition trial push
};
